#pragma once

#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY
// #define HOLD_ON_OTHER_KEY_PRESS
#define PERMISSIVE_HOLD
// #define PERMISSIVE_HOLD_PER_KEY
// #define BILATERAL_COMBINATIONS
// For home row mods
//#define HRM
// #define IGNORE_MOD_TAP_INTERRUPT

#define ADAPTIVE_TERM 150

#define COMBO_STRICT_TIMER
#define COMBO_TERM 20
// #define NO_ACTION_ONESHOT
#define SPLIT_MODS_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
#define TAPPING_FORCE_HOLD_PER_KEY
#define COMBO_ONLY_FROM_LAYER 0

// to give CTL_T(KC_L/RPRN) for HRM
// #define LSPO_KEYS KC_LCTL, LSPO_MOD, LSPO_KEY
// #define RSPC_KEYS KC_RCTL, RSPC_MOD, RSPC_KEY
